################################################################################
# Appveyor-CI
# -----------
# Script for setting up Appveyor CI environment
################################################################################

# Setup
################################################################################

version: "{build}"

# Agents
################################################################################

os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

# Stages
################################################################################

install:
  - cmd: .\.appveyor\install.cmd

before_build:
  - set CXXFLAGS="/permissive-"
  - cmd: .\.appveyor\before-build.cmd

build:
  project: build\string_view_standalone.sln
  parallel: true
  verbosity: normal

test_script:
  - cmd: .\.appveyor\test.cmd